# Generated by Django 3.0.3 on 2020-05-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=100)),
                ('sender_email', models.CharField(default='', max_length=100)),
                ('feedback_topic', models.CharField(default='', max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regestration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('m_no', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(default='', max_length=100)),
                ('index', models.PositiveIntegerField(default=0)),
                ('u_hash', models.CharField(default='', max_length=200)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('bitcoin', models.FloatField(default=0.0, max_length=10)),
                ('u_prev_hash', models.CharField(default='', max_length=200)),
                ('timestamp', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=500)),
                ('receiver', models.CharField(default='', max_length=500)),
                ('amount', models.FloatField(default=0.0)),
                ('bitcoin', models.FloatField(default=0.0, max_length=10)),
                ('time', models.CharField(default='', max_length=200)),
                ('cut_money', models.FloatField(default=0.0)),
                ('send_notes', models.TextField(default='')),
                ('receive_notes', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Regestration')),
            ],
        ),
    ]
